// b6as port of libc/besm6/madlen/b_dtoi.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Convert a native floating-point value to a signed int, truncated toward zero (C
// semantics):  result = (int)x.
//
// Helper convention: the operand x is in the accumulator A (no stack operand); the result
// is returned in A.
//
// x arrives as a normalized FP word (exponent biased by 64).  Adding INT-format 0.0
// (exponent 0150B, the =:64 literal) with normalization+rounding suppressed re-aligns the
// mantissa to the INT exponent: the bits below 2^0 are shifted out and the integer part
// lands in bits 40-1.  That shift drops the fraction, but for a two's-complement (negative)
// mantissa it rounds toward MINUS infinity, not toward zero.  To get C truncation toward
// zero we realign the MAGNITUDE |x| (where floor == truncate) and reapply the sign
// afterwards -- the same absolute-value method b/div uses.
//
// Values with |x| >= 2^40 do not fit the 41-bit signed range and overflow
// (implementation-defined, C11 6.3.1.4).
//
    .text
    .globl b$dtoi
b$dtoi:
 15 atx                     // push x as the sign reference: mem[r15-1] := x ; r15 += 1
    ntr                     // R := 0: full FP mode for the absolute value
 15 avx -1                  // A := |x|  (AVX negates A iff x at r15-1 < 0)
    ntr 3                   // R := 3: suppress normalize + round for integer extraction
    a+x #0'64               // realign |x| to the INT exponent, dropping the fraction
 15 avx -1                  // reapply sign: negate the magnitude iff x < 0
 15 utm -1                  // pop x: r15 := entry
    aax #037'7777'7777'7777 // mask off the exponent -> raw 41-bit signed int
 13 uj                      // return to caller (return address in r13)
