// b6as port of libc/besm6/madlen/b_dtou.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Convert a native floating-point value to a 48-bit unsigned integer, truncated toward
// zero:  result = (unsigned)x.
//
// Helper convention: the operand x is in the accumulator A (no stack operand); the result
// is returned in A.
//
// The realign-and-mask of b/dtoi only recovers the low 41 bits, so for the full unsigned
// range mirror b/utod's split in reverse: peel off the high 24 bits, then the low 24 bits,
// and reassemble.
// hi = trunc(x * 2^-24)               (the high 24 bits, < 2^24)
// lo = trunc(x - (double)hi * 2^24)   (the low  24 bits, < 2^24)
// result = (hi << 24) | lo
// Each truncation is the b/dtoi realign trick (=:64 add under suppressed normalization,
// then mask).  Both intermediates are non-negative, so no sign handling is needed.
// (unsigned) of a negative or >= 2^48 value is undefined, as in C.
//
// Stack picture in the right margin ("/" separates the stack from the accumulator):
//
    .text
    .globl b$dtou
b$dtou:
 15 atx                     // push x ; r15 += 1                        x /
                            // --- hi = trunc(x * 2^-24) ---
    ntr                     // R := 0: full FP mode for the multiply
    a*x #0'245              // A := x * 2^-24
    ntr 3                   // R := 3: suppress normalize + round
    a+x #0'64               // realign -> truncate toward zero
    aax #037'7777'7777'7777 // mask -> hi  (integer, < 2^24)
 15 atx                     // push hi ; r15 += 1                       x hi /
                            // --- lo = trunc(x - (double)hi * 2^24) ---
    aox #0'64               // A := INT-format hi
    ntr                     // R := 0: full FP mode
    a+x                     // normalize: A := (double)hi
    a*x #0'545              // A := (double)hi * 2^24
 15 x-a -2                  // A := x - (double)hi*2^24 = lo  (x at r15-2)
    ntr 3                   // R := 3: suppress normalize + round
    a+x #0'64               // realign -> truncate toward zero
    aax #037'7777'7777'7777 // mask -> lo  (integer, < 2^24)
 15 atx                     // push lo ; r15 += 1                       x hi lo /
                            // --- result = (hi << 24) | lo ---
 15 xta -2                  // A := hi  (at r15-2)
    asn 64-24               // A := hi << 24
 15 aox -1                  // A := (hi << 24) | lo  (lo at r15-1)
 15 utm -3                  // drop x, hi, lo: r15 := entry
 13 uj                      // return to caller (return address in r13)
