// b6as port of libc/besm6/madlen/b_eq.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute relational Equal operation.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$eq
b$eq:
 15 aex
    uza true
    xta
 13 uj

true:
    xta #01
 13 uj
