// b6as port of libc/besm6/madlen/b_flt.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Floating-point relational Less Than:  result = (a < b).
// Pop two FP values from stack (a at mem[r15-1], b in A).  Push raw 0/1 back.
//
// NTR (R := 0) selects full FP mode so the subtract normalizes and rounds: the
// additive sign then reflects the mathematical difference, and equal operands
// yield an exact zero.  Before returning, each path restores R := 7 (the integer
// mode b/save leaves in place) so the caller's following integer ops are correct.
// The NTR 7 must follow the branch, since NTR overwrites the omega flag U1A tests.
//
    .text
    .globl b$flt
b$flt:
    ntr         // R := 0: full FP mode for the subtract
 15 x-a         // A := a - b (FP); additive sign set
    u1a true    // a - b < 0  ->  a < b
    xta         // A := 0 (false)
    ntr 7       // restore integer mode for the caller
 13 uj

true:
    xta #01     // A := 1 (true)
    ntr 7       // restore integer mode for the caller
 13 uj
