// b6as port of libc/besm6/madlen/b_ge.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute relational Greater or Equal operation.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$ge
b$ge:
 15 x-a
    uza true
    xta
 13 uj
//
true:
    xta #01
 13 uj
