// b6as port of libc/besm6/madlen/b_le.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute relational Less Or Equal operation.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$le
b$le:
 15 a-x
    uza true
    xta
 13 uj

true:
    xta #01
 13 uj
