// b6as port of libc/besm6/madlen/b_lsh.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute a left shift operation A << B.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$lsh
b$lsh:
    aex #0177       // ~B is the same as -B-1
    sti 14          // r14 = -B-1, pop A from stack
 14 asn 64 + 1      // A <<= -r14-1
 13 uj
