// b6as port of libc/besm6/madlen/b_lt.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute relational Less Than operation.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$lt
b$lt:
 15 x-a
    u1a true
    xta
 13 uj

true:
    xta #01
 13 uj
