// b6as port of libc/besm6/madlen/b_mul.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Multiply two 41-bit signed integers.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$mul
b$mul:
    aox #0'64
 15 stx
    aox #0'64
    ntr 2
 15 a*x 1
    ntr 3
    a+x #0'64
    aax #037'7777'7777'7777
 13 uj
