// b6as port of libc/besm6/madlen/b_mul.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Multiply two 41-bit signed integers.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$mul
b$mul:
    aox #06400000000000000
 15 stx
    aox #06400000000000000
    ntr 2
 15 a*x 1
    ntr 3
    a+x #06400000000000000
    aax #037777777777777
 13 uj
