// b6as port of libc/besm6/madlen/b_ne.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute relational Not Equal operation.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$ne
b$ne:
 15 aex
    u1a true
    xta
 13 uj
//
true:
    xta #01
 13 uj
