// b6as port of libc/besm6/madlen/b_not.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute logical NOT operation.
//
    .text
    .globl b$not
b$not:
    aex
    uza true
    xta
 13 uj

true:
    xta #01
 13 uj
