// b6as port of libc/besm6/madlen/b_padd.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Add a signed byte count to a char*/void* base, returning a normalized fat pointer.
// Helper convention: the base a is on the stack top (mem[r15-1]); the signed byte delta is
// in A; the result is left in A and a is popped (net r15 = entry - 1).
//
// Fat-pointer layout: bit 48 = marker, bits 47-45 = offset_enc (exponent = 64 + enc*8),
// bits 15-1 = word address.  byte#(from the MSB) = 5 - offset_enc; offset_enc 5 = byte#0.
// A bare base (marker bit clear, e.g. an array word address or a struct address) is taken
// to start at byte#0 (the MSB).  The result always has the marker set.
//
// m     = byte# + delta                 (signed byte index from the base word's MSB)
// word' = word + floor(m / 6)
// enc'  = 5 - (m - 6*floor(m/6))         (the floored remainder, 0..5)
//
// floor(m/6) uses the hardware FP divide: dividing two normalized INT-format operands and
// masking the fraction rounds toward -infinity (a true floor), so no sign juggling needed.
//
// THE EIGHT TEMPORARIES ARE A STACK FRAME, NOT STATIC CELLS, AND THAT IS LOAD-BEARING.
// This helper must be REENTRANT: it is interruptible at every instruction, and what
// interrupts it walks char pointers of its own -- a Unix kernel's clock tick reaching a
// `char' struct member, or a signal handler in a user program.  While the cells were in
// .bss, a tick landing inside this routine ran a handler whose own b$padd overwrote them,
// and the outer call resumed and finished with the inner one's base and word: a pointer to
// entirely the wrong object, with no fault and no diagnostic to mark it.  (Found in the Unix
// v7 port, where it deadlocked the first exec: iget() read a `char' i_flag through a pointer
// that a clock tick had turned into a pointer to proc[].)  b_umul.s has kept its temporaries
// on the stack from the start; these five pointer helpers (b$padd, b$pinc, b$pdec, b$pdiff,
// b$stb) were the last carrying the Madlen original's static cells.
//
// The frame is reserved by ADVANCING r15, not by writing above it: an interrupt builds its
// own frame at r15, so scratch left above r15 is scratch waiting to be overwritten.  The
// base is read where the caller left it rather than popped into a slot, and the closing
// `utm' releases the frame and pops it in one.  Slots are addressed by NEGATIVE offset from
// r15 -- with index register 15 a ZERO address field is the machine's stack mode (auto
// push/pop), so every offset here must be nonzero.
//
// `ttab' stays in .data: it is read-only, so sharing it is safe.  Its indexed lookups spell
// the `utc' out by hand, since `< >' would apply the index register to the generated `utc'
// as well and double-count it.  `utc' touches neither A nor R.
//
    .text
    .globl b$padd
b$padd:
 15 utm 8               // reserve: base at -9 (the caller's), delta at -8, word at -7,
 15 atx -8              //   m at -6, six at -5, q at -4, q2 at -3, q6 at -2, encw at -1
 15 xta -9              // A = the base a
    aax #07'7777        // word address (bits 15-1)
 15 atx -7

// byte# from the MSB
 15 xta -9              // A = base
    aax #0'40           // test the marker (bit 48)
    uza bare            // marker clear -> byte# = 0
 15 xta -9
    asn 64+44           // offset_enc -> bits 3-1
    aax #07
    ati 11
    utc ttab
 11 xta                 // byte# = 5 - offset_enc  (EA = 0 + M11 + C)
    uj havebyte
bare:
    xta #00
havebyte:
 15 a+x -8              // m = byte# + delta  (R = 7 at entry: raw integer add)

// Bias m by 6*K (K = 0200000 = 65536 words) so the dividend is non-negative: INT-format
// divide misreads a negative two's-complement mantissa, and the BESM-6 address space is
// only 15 bits, so 6K exceeds any in-bounds byte span.  floor((m+6K)/6) = floor(m/6) + K
// and (m+6K) mod 6 = m mod 6, so K is subtracted back from the quotient below.
    a+x #0140'0000      // M = m + 6K  (>= 0)
 15 atx -6

// q = floor(M / 6): divide as normalized FP, then mask the fraction.  INT-format operands
// must be normalized first (a+x mem[0]=0), as in b/utod.
    ntr                 // R := 0: full FP mode (normalize + round)
    xta #06
    aox #0'64           // INT-format 6
    a+x                 // normalize -> (double)6
 15 atx -5              // six
 15 xta -6              // m
    aox #0'64           // INT-format M
    a+x                 // normalize -> (double)M
 15 a/x -5              // (double)M / (double)6
    ntr 3               // R := 3: suppress normalize + round
    a+x #0'64           // re-align to the INT exponent, dropping the fraction
    aax #037'7777'7777'7777 // raw quotient q = floor(M/6)
 15 atx -4              // q
                        // 6*q = 4q + 2q
    asn 64-1            // 2q
 15 atx -3              // q2
 15 xta -4              // q
    asn 64-2            // 4q
 15 arx -3              // 6q
 15 atx -2              // q6
                        // r = m - 6q  (0..5)
    ntr 7               // R := 7: raw integer additive mode
 15 xta -6              // m
 15 a-x -2              // - q6
    ati 11
                        // enc' = 5 - r
    utc ttab
 11 xta                 // EA = 0 + M11 + C
    asn 64-44           // offset_enc' -> bits 47-45
    aox #0'40           // set marker
 15 atx -1              // encw

// word' = word + q - K   (undo the bias added to the dividend)
 15 xta -7              // word
 15 a+x -4              // + q
    a-x #020'0000
    aax #07'7777
 15 aox -1              // | encw
 15 utm -9              // release the frame AND pop the caller's base (net r15 = entry - 1)
 13 uj

// ttab[i] = 5 - i  (octal)
    .data
ttab:
    .word 05
    .word 04
    .word 03
    .word 02
    .word 01
    .word 00
