// b6as port of libc/besm6/madlen/b_pdiff.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Difference of two char*/void* fat pointers: p - q -> ptrdiff_t byte count.
// Helper convention: the minuend a (= p) is on the stack top (mem[r15-1]); the subtrahend
// b (= q) is in A; the result a - b is left in A and a is popped (net r15 = entry - 1).
//
// Fat-pointer layout: bit 48 = marker, bits 47-45 = offset_enc (exponent = 64 + enc*8),
// bits 15-1 = word address.  byte#(from the MSB) = 5 - offset_enc; offset_enc 5 = byte#0.
// A bare base (marker bit clear, e.g. an array word address or a struct address) starts at
// byte#0 (the MSB).  The absolute byte position of a fat pointer is
//
// abs = word*6 + byte#          (byte# = 5 - offset_enc, or 0 if the marker is clear)
//
// and the result is abs(a) - abs(b).  sizeof(char) == 1, so no scaling is needed.  All raw
// integer mode (R = 7 at entry): no normalization, no division.
//
    .text
    .globl b$pdiff
b$pdiff:
    atx b  // save b (q), in A at entry
 15 xta  // pop a (p)
    atx a
// --- abs(a) = word_a*6 + byte#_a -> aa ---
    aax #077777  // word_a (bits 15-1)
    atx w
    asn 64-1  // 2*word
    atx w2
    xta w
    asn 64-2  // 4*word
    a+x w2  // 6*word_a
    atx aa
    xta a
    aax #04000000000000000  // test the marker (bit 48)
    uza abare  // marker clear -> byte# = 0
    xta a
    asn 64+44  // offset_enc -> bits 3-1
    aax #07
    ati 11
 11 xta ttab  // byte# = 5 - offset_enc
    a+x aa
    atx aa
// --- abs(b) = word_b*6 + byte#_b -> bb ---
abare:
    xta b
    aax #077777  // word_b (bits 15-1)
    atx w
    asn 64-1
    atx w2
    xta w
    asn 64-2
    a+x w2  // 6*word_b
    atx bb
    xta b
    aax #04000000000000000  // test the marker (bit 48)
    uza bbare  // marker clear -> byte# = 0
    xta b
    asn 64+44  // offset_enc -> bits 3-1
    aax #07
    ati 11
 11 xta ttab  // byte# = 5 - offset_enc
    a+x bb
    atx bb
// --- result = abs(a) - abs(b) ---
bbare:
    xta aa
    a-x bb  // R = 7: raw integer subtract (a-x sets additive w)
    aox  // OR mem[0]=0: ACC unchanged, restore logical w-mode
 13 uj
//
    .bss
a:
    . = . + 1
b:
    . = . + 1
w:
    . = . + 1
w2:
    . = . + 1
aa:
    . = . + 1
bb:
    . = . + 1
// ttab[i] = 5 - i  (octal)
    .data
ttab:
    .word 05
    .word 04
    .word 03
    .word 02
    .word 01
    .word 00
