// b6as port of libc/besm6/madlen/b_pdiff.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Difference of two char*/void* fat pointers: p - q -> ptrdiff_t byte count.
// Helper convention: the minuend a (= p) is on the stack top (mem[r15-1]); the subtrahend
// b (= q) is in A; the result a - b is left in A and a is popped (net r15 = entry - 1).
//
// Fat-pointer layout: bit 48 = marker, bits 47-45 = offset_enc (exponent = 64 + enc*8),
// bits 15-1 = word address.  byte#(from the MSB) = 5 - offset_enc; offset_enc 5 = byte#0.
// A bare base (marker bit clear, e.g. an array word address or a struct address) starts at
// byte#0 (the MSB).  The absolute byte position of a fat pointer is
//
// abs = word*6 + byte#          (byte# = 5 - offset_enc, or 0 if the marker is clear)
//
// and the result is abs(a) - abs(b).  sizeof(char) == 1, so no scaling is needed.  All raw
// integer mode (R = 7 at entry): no normalization, no division.
//
// The temporaries are a stack frame rather than static cells, for the reentrancy reason
// b_pinc.s spells out.  The frame is reserved by ADVANCING r15 (an interrupt builds its own
// frame at r15, so scratch above it would be overwritten); `a' is read where the caller left
// it rather than popped into a slot, and the closing `utm' releases the frame and pops it in
// one.  No slot may sit at offset 0: with index register 15 a zero address field is the
// machine's stack mode.
//
// `ttab' stays in .data: it is read-only, so sharing it is safe.  Its indexed lookups spell
// the `utc' out by hand, since `< >` would apply the index register to the generated `utc'
// as well.
//
    .text
    .globl b$pdiff
b$pdiff:
 15 utm 5           // reserve: a at -6 (the caller's), b at -5, w at -4, w2 at -3,
 15 atx -5          //          aa at -2, bb at -1.  b (q) := A, in A at entry

// --- abs(a) = word_a*6 + byte#_a -> aa ---
 15 xta -6          // A = a (p)
    aax #07'7777    // word_a (bits 15-1)
 15 atx -4          // w := word_a
    asn 64-1        // 2*word
 15 atx -3          // w2 := 2*word
 15 xta -4          // A = w
    asn 64-2        // 4*word
 15 a+x -3          // 6*word_a
 15 atx -2          // aa := 6*word_a
 15 xta -6          // A = a
    aax #0'40       // test the marker (bit 48)
    uza abare       // marker clear -> byte# = 0
 15 xta -6          // A = a
    asn 64+44       // offset_enc -> bits 3-1
    aax #07
    ati 11
    utc ttab
 11 xta             // byte# = 5 - offset_enc  (EA = 0 + M11 + C)
 15 a+x -2
 15 atx -2          // aa += byte#_a

// --- abs(b) = word_b*6 + byte#_b -> bb ---
abare:
 15 xta -5          // A = b (q)
    aax #07'7777    // word_b (bits 15-1)
 15 atx -4          // w := word_b
    asn 64-1
 15 atx -3          // w2 := 2*word
 15 xta -4
    asn 64-2
 15 a+x -3          // 6*word_b
 15 atx -1          // bb := 6*word_b
 15 xta -5          // A = b
    aax #0'40       // test the marker (bit 48)
    uza bbare       // marker clear -> byte# = 0
 15 xta -5          // A = b
    asn 64+44       // offset_enc -> bits 3-1
    aax #07
    ati 11
    utc ttab
 11 xta             // byte# = 5 - offset_enc  (EA = 0 + M11 + C)
 15 a+x -1
 15 atx -1          // bb += byte#_b

// --- result = abs(a) - abs(b) ---
bbare:
 15 xta -2          // A = aa
 15 a-x -1          // R = 7: raw integer subtract (a-x sets additive w)
    aox             // OR mem[0]=0: ACC unchanged, restore logical w-mode
 15 utm -6          // release the frame AND pop the caller's `a' (net r15 = entry - 1)
 13 uj

// ttab[i] = 5 - i  (octal)
    .data
ttab:
    .word 05
    .word 04
    .word 03
    .word 02
    .word 01
    .word 00
