// b6as port of libc/besm6/madlen/b_pdec.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Decrement a char*/void* fat pointer by one byte (char*--): move toward the MSB.
// Mirror of b/pinc: advancing back one byte increments offset_enc; at offset_enc 5 it
// wraps to 0 and the word address steps back by one.  Operand in A, result in A;
// R is left unchanged.  See b/pinc for the fat-pointer layout.
//
    .text
    .globl b$pdec
b$pdec:
    atx p
    aax #07'7777                // A = word address (bits 15-1)
    atx w
    xta p
    asn 64+44                   // offset_enc -> bits 3-1
    aax #07                     // offset_enc (0..5)
    atx enc
    aex #05                     // enc XOR 5 == 0  iff  offset_enc == 5
    uza wrap                    // offset_enc == 5 -> wrap to 0, step word back
    xta enc
    arx #01                     // offset_enc + 1
    aax #07                     // re-mask to 3 bits (mirror b/pinc)
    asn 64-44                   // offset_enc' -> bits 47-45
    aox #0'40                   // set marker (bit 48)
    aox w                       // OR in the word address
 13 uj
wrap:
    xta w
    arx #07777'7777'7777'7776   // word -= 1 (end-around add of -1)
    aax #07'7777
    aox #0'40                   // marker + offset_enc 0 (LSB of the previous word)
 13 uj

    .bss
p:
    . = . + 1
w:
    . = . + 1
enc:
    . = . + 1
