// b6as port of libc/besm6/madlen/b_pinc.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Increment a char*/void* fat pointer by one byte (char*++): move toward the LSB.
// The fat pointer holds the word address in bits 15-1 and the byte offset code (offset_enc,
// = 64 + enc*8 in the exponent field) in bits 47-45, with the marker in bit 48.
// offset_enc 5 = byte#0 (MSB, first byte), offset_enc 0 = byte#5 (LSB, last byte).
// Advancing one byte decrements offset_enc; at offset_enc 0 it wraps to 5 and the word
// address advances by one.  Operand in A, result in A; R is left unchanged.
//
    .text
    .globl b$pinc
b$pinc:
    atx p
    aax #07'7777    // A = word address (bits 15-1)
    atx w
    xta p
    asn 64+44       // offset_enc -> bits 3-1
    aax #07         // offset_enc (0..5)
    uza wrap        // offset_enc == 0 -> wrap to 5, bump word
    arx #07         // offset_enc - 1 as (enc+7) mod 8: a positive cyclic add,
    aax #07         // so enc==1 yields 0 (a -1 add gives all-ones -0 -> masks to 7)
    asn 64-44       // offset_enc' -> bits 47-45
    aox #0'40       // set marker (bit 48)
    aox w           // OR in the word address
 13 uj
wrap:
    xta w
    arx #01         // word += 1
    aox #0'64       // marker + offset_enc 5 (MSB of the next word)
 13 uj

    .bss
p:
    . = . + 1
w:
    . = . + 1
