// b6as port of libc/besm6/madlen/b_ret.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Restore registers from the stack.
// Called on exit from a C function.
//
    .text
    .globl b$ret
b$ret:
  6 mtj 14
  7 mtj 15
  7 stx -5
    sti 5
    sti 6
    sti 7
    sti 13
 14 mtj 15
 13 uj
