// b6as port of libc/besm6/madlen/b_rsh.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute a right shift operation A >> B.
// Pop two values from stack.
// Push result back.
//
    .text
    .globl b$rsh
b$rsh:
    sti 14  // r14 = B, pop A from stack
 14 asn 64  // A >>= r14
 13 uj
