// b6as port of libc/besm6/madlen/b_save0.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Save registers on the stack.
// Called on entry to each C function with no parameters.
//
    .text
    .globl b$save0
b$save0:
 15 mtj 14
 14 utm -1
    its 7
    its 6
    its 5
    its
 14 mtj 6
 15 mtj 7
    ntr 7
 13 uj
