// b6as port of libc/besm6/madlen/b_stb.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Store one byte through a char*/void* fat pointer (read-modify-write).
// Lightweight helper convention:
// a = fat pointer  — on the stack top (mem[r15-1]); popped by this helper.
// b = byte value   — in the accumulator.
// The fat pointer encodes the word address in bits 15-1 and the byte offset in
// bits 47-45 (its exponent field = 64 + offset*8).  Offset 0 = byte #5 (LSB),
// offset 5 = byte #0 (MSB).  r6/r7 are preserved.
//
// Every reference below to this file's own .bss/.data goes through a `utc` long-address
// escape; see b_padd.s for why (b6as has no Madlen `,base,`, and a short address field is
// only 12 bits wide, silently masked).  `< sym >` expands to `utc sym` + the instruction;
// the indexed `mask`/`shift` lookups spell the `utc` out by hand, since `< >` would apply
// the index register to the generated `utc` as well.  `utc` touches neither A nor R.
//
    .text
    .globl b$stb
b$stb:
    aax #0377   // mask the byte value to 8 bits
    atx <val>   // save b
 15 xta         // pop the fat pointer a from the stack
    atx <ptr>   // save the pointer (for the word address)

// extract the byte offset (bits 47-45) into M11
    asn 64+44   // shift offset down: bits 47-45 -> bits 3-1
    aax #07     // keep the 3-bit offset (0..5)
    ati 11

// word address (bits 15-1) into M12
    xta <ptr>
    ati 12

// read-modify-write the containing word
 12 xta         // A = word at the pointer's word address
    utc mask
 11 aax         // clear the target byte (EA = 0 + M11 + C)
    atx <word>
    xta <val>   // A = byte value
    utc shift
 11 asx         // shift it left into the target byte position (EA = 0 + M11 + C)
    aox <word>  // OR it into the cleared word
 12 atx         // write the word back
    xta <val>   // return the stored byte in A
 13 uj

    .bss
val:
    . = . + 1
ptr:
    . = . + 1
word:
    . = . + 1

// mask[offset]: clears the target byte (offset 0 = LSB byte #5 .. 5 = MSB byte #0)
    .data
mask:
    .word 07777'7777'7777'7400
    .word 07777'7777'7760'0377
    .word 07777'7777'0017'7777
    .word 07777'7400'7777'7777
    .word 07760'0377'7777'7777
    .word 00017'7777'7777'7777

// shift[offset]: OCT exponent = 64 - offset*8, so ASX left-shifts by offset*8
shift:
    .word 0'40
    .word 0'34
    .word 0'30
    .word 0'24
    .word 0'20
    .word 0'14
