// b6as port of libc/besm6/madlen/b_tout.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Write line to stdout.
//
    .text
    .globl b$tout
b$tout:
    ati 12
    utc info
    $71
 13 uj
//
info:
 12 $40
    $00
