// b6as port of libc/besm6/madlen/b_uadd.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Add two 48-bit unsigned integers, modulo 2^48: a+b.
// Pop two values from stack, push result back.
// Value a is in stack, value b on accumulator.
//
    .text
    .globl b$uadd
b$uadd:
    ntr 8+3
    uza b_large  // jump when B[48] = 1
 15 xts -2  // push B on stack, extract A
    ntr 8+3
    uza a_large  // jump when A[48] = 1
//
 15 arx  // add A[47:1] + B[47:1]
 15 utm -1  // drop A from stack
    aox  // OR mem[0]=0: ACC unchanged, restore logical w-mode
 13 uj
//
b_large:
    aex #04000000000000000  // clear bit 48 of B
 15 xts -2  // push B on stack, extract A
    ntr 8+3
    uza ab_large  // jump when A[48] = 1
 15 arx  // add A[47:1] + B[47:1]
    aex #04000000000000000  // restore bit 48 contribution
 15 utm -1  // drop A from stack
 13 uj
//
a_large:
    aex #04000000000000000  // clear bit 48 of A
 15 arx  // add A[47:1] + B[47:1]
    aex #04000000000000000  // restore bit 48 contribution
 15 utm -1  // drop A from stack
 13 uj
//
ab_large:
    aex #04000000000000000  // clear bit 48 of A
 15 arx  // add A[47:1] + B[47:1]
 15 utm -1  // drop A from stack
    aox  // OR mem[0]=0: ACC unchanged, restore logical w-mode
 13 uj
