// b6as port of libc/besm6/madlen/b_ult.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Unsigned less than.
// Pop two values from stack, push result back.
//
    .text
    .globl b$ult
b$ult:
 15 aex  // A ^ B
 15 atx  // push to stack
    yta  // get B from RMR
 15 apx  // pop A^B from stack, pack by B
    asn 64+47  // get bit 48
 13 uj
