// b6as port of libc/besm6/madlen/b_ule.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Unsigned less than or equal.
// Pop two values from stack, push result back.
//
    .text
    .globl b$ule
b$ule:
 15 aex -1  // A ^ B
 15 atx  // push A^B to stack
 15 xta -2  // get A from stack
 15 apx  // pop A^B from stack, pack by A
    asn 64+47  // get bit 48
 15 utm -1  // pop stack
    aex #01  // invert
 13 uj
