// b6as port of libc/besm6/madlen/b_umod.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Unsigned remainder of two 48-bit integers:  result = a % b  (full 48-bit range).
//
// Helper convention: dividend a is on the stack at mem[r15-1], divisor b is in the
// accumulator A, the remainder is returned in A.  The caller pushed a with one XTS, so
// this helper pops exactly one word (net r15 = entry - 1) before returning.
//
// The signed b/mod shares b/div's hardware-FP bridge (40-bit mantissa, bit 48 read as a
// sign), so it is wrong for unsigned operands >= 2^40 or with bit 48 set -- the same flaw
// b/udiv (task #14a) fixes for unsigned divide.  b/umod computes the full-width residue
// from the identity
// r = a - (a / b) * b
// reusing the proven full-width helpers b/udiv, b/umul and b/usub.  Each shares this
// routine's convention (operand a on the stack, b in A, result in A, pops one word).
//
// CALL clobbers r13, so the entry return address is saved in the frame.  b/umul and b/usub
// touch only r13/r14/r15 (+A/Y); b/udiv additionally uses r10/r11 -- but none touch r12, so
// the frame base r12 survives all three nested calls.  Frame (relative to r12): a = r12-1,
// b = r12+0, r13 = r12+1, scratch = r12+2.
//
// NB: like b/udiv this routine has NO ",base," directive.  b/udiv (via b/div / b/mod) and
// b/umul reload r14 with their own base and never restore it, so a base-relative literal
// access after such a call would read the wrong word.  This routine uses no literals; labels
// resolve absolutely.
//
    .text
    .globl b$umod
b$umod:
 15 atx  // push b: mem[E] := b, r15 := E+1
    ita 13  // A := saved return address (r13)
 15 atx  // push r13: mem[E+1] := r13, r15 := E+2
 15 mtj 12  // r12 := r15 = E+2
 12 utm -2  // r12 := E  (a = r12-1, b = r12, r13 = r12+1)
 15 utm 1  // reserve scratch slot r12+2: r15 := E+3
// q = b/udiv(a, b)
 12 xta -1  // A := a
 12 xts  // push a, A := b   (load via r12+0)
 13 vjm b$udiv  // A := q = a / b ; helper pops one word -> r15 = E+3
 12 atx 2  // scratch := q
// p = b/umul(q, b)
 12 xta 2  // A := q
 12 xts  // push q, A := b   (load via r12+0)
 13 vjm b$umul  // A := p = q * b ; r15 = E+3
 12 atx 2  // scratch := p  (q no longer needed)
// r = b/usub(a, p) = a - p
 12 xta -1  // A := a
 12 xts 2  // push a, A := p   (load via r12+2)
 13 vjm b$usub  // A := r = a - p ; r15 = E+3
// restore r13, return r
 12 atx 2  // scratch := r  (free A to reload r13)
 12 xta 1  // A := saved r13
    ati 13  // r13 := A
 12 xta 2  // A := r  (result)
 15 utm -4  // drop the frame: r15 := entry - 1  (E+3 -> E-1)
 13 uj  // return to caller
