// b6as port of libc/besm6/madlen/b_uneg.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Compute unary negate operation for unsigned value.
//
    .text
    .globl b$uneg
b$uneg:
    aox                         // OR mem[0]=0: ACC unchanged, set logical w so uza tests x==0
 13 uza                         // -0u -> 0u  (returns with logical w from the aox above)
    aex #07777'7777'7777'7777   // all ones
    arx #01                     // ~x + 1   (arx sets multiplicative w)
    aox                         // OR mem[0]=0: ACC unchanged, restore logical w-mode
 13 uj
