// b6as port of libc/besm6/madlen/b_usub.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Subtract two 48-bit unsigned integers, modulo 2^48: a-b.
// Pop two values from stack, push result back.
// Value a is in stack, value b on accumulator.
//
    .text
    .globl b$usub
b$usub:
    ntr 7                       // B is on accumulator
    uza b_zero                  // jump when B 0= 0
    aex #07777'7777'7777'7777   // all ones
    arx #01                     // negate B
    uj b$uadd                   // compute A + (-B)

b_zero:
    stx                         // pop A from stack
 13 uj
