// b6as port of libc/besm6/madlen/b_utod.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Convert a 48-bit unsigned integer to a native floating-point value:  result = (double)u.
//
// Helper convention: the operand u is in the accumulator A (no stack operand); the result
// is returned in A.
//
// The inline signed int->FP trick (OR the INT exponent, then normalize) cannot be used on
// an unsigned word: a full 48-bit value carries data in the exponent field (bits 48-42)
// and would have bit 41 misread as the FP sign.  Instead split u into two 24-bit halves
// u = hi * 2^24 + lo        (hi = bits 48-25, lo = bits 24-1)
// each of which is < 2^24 and so fits the 40-bit mantissa exactly, convert each half via
// the INT-format-then-normalize trick, and recombine in floating point:
// (double)u = (double)hi * 2^24 + (double)lo
// Inputs with more than 40 significant bits round to the 40-bit mantissa (unavoidable).
//
// Stack picture in the right margin ("/" separates the stack from the accumulator):
//
    .text
    .globl b$utod
b$utod:
 15 atx  // push u: mem[r15-1] := u ; r15 += 1        u /
// --- (double)hi * 2^24 ---
    asn 64+24  // A := u >> 24 = hi   (logical shift, zero fill)
    aox #06400000000000000  // A := INT-format hi
    ntr  // R := 0: full FP mode (normalize + round)
    a+x  // normalize: A := (double)hi   (A+X mem[0]=0)
    a*x #05450000000000000  // A := (double)hi * 2^24
 15 atx  // push hi24: mem[r15-1] := A ; r15 += 1      u hi24 /
// --- (double)lo, then add ---
 15 xta -2  // A := u  (at r15-2)
    aax #077777777  // A := u & (2^24-1) = lo
    aox #06400000000000000  // A := INT-format lo
    ntr  // R := 0: full FP mode
    a+x  // normalize: A := (double)lo
 15 a+x -1  // A := (double)lo + hi24 = (double)u
    ntr 7  // R := 7: restore integer mode for the caller
 15 utm -2  // drop u, hi24: r15 := entry
 13 uj  // return to caller (return address in r13)
