// b6as port of libc/besm6/madlen/exit.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// Terminate the program.
// No return.
//
    .text
    .globl exit
exit:
    $74
