// b6as port of libc/besm6/madlen/ldexp.madlen (generated by U2; see the
// Madlen original for full commentary). Runtime-helper names use $ (b6as).
//
// double ldexp(double x, int n) -- return x * 2^n.
// Entry: x at mem[r15-1], n in the accumulator.  Result in the accumulator.
//
    .text
    .globl ldexp
ldexp:
    aex #0100  // n + 64
    asn 64-41  // (n+64) << 41  into the exponent field
 15 xts -2  // x             push stack
 15 e+x  // x * 2^n       pop stack
 15 utm -1  // drop x
 13 uj  // return
